CREATE TABLE trd2022_event(  
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    ID_CLIENT int,
    EVENT_TYPE varchar(7) NOT NULL,
    REC_TYPE VARCHAR(9),
    ASSET VARCHAR(13),
    INITIAL_PRICE DOUBLE,
    FINAL_PRICE DOUBLE,
    INITIAL_QTY DOUBLE,
    FINAL_QTY DOUBLE,
    VALORIZATION DOUBLE,
    INFO VARCHAR(255),
    MOMENT DATETIME,
    FOREIGN KEY (ID_CLIENT) REFERENCES trd2022_client(ID)
);

CREATE TABLE trd2022_client(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    name VARCHAR(60),
    EMAIL VARCHAR(230),
    PASSWORD VARCHAR(22),
    DT_REGISTER DATETIME
)